=== DaisukeBekki/JSeM/data/v1.0/jsem.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT jsem-dataset (problem|comment)+>

<!-- miscellaneous comment, not necessarily on a specific problem -->
<!ELEMENT comment (#PCDATA)>

<!ELEMENT problem (link?,description?,p+,q?,h,a?,note*)>

<!-- problem -->
<!ATTLIST problem
  jsem_id CDATA #REQUIRED
  answer (yes|no|unknown|undef|unacceptable|weakacceptable|infelicitous) #REQUIRED
  jsem_nonstandard (true) #IMPLIED
  language (fa|de|zh|jp) #REQUIRED
  phenomena CDATA #IMPLIED
  inference_type (entailment|presupposition|CI|GCI|PCI) #IMPLIED
  >
<!--  inference_type CDATA -->

<!-- link element shows the information of corresponding FraCaS entry -->
<!ELEMENT link (#PCDATA)>
<!ATTLIST link
  resource CDATA #REQUIRED
  link_id CDATA #REQUIRED
  translation (yes|no|unknown) #IMPLIED
  same_phenomena (yes|no|unknown) #IMPLIED
  >

<!ELEMENT description (#PCDATA)>

<!-- premise elements, possibly more than one -->
<!ELEMENT p (script,english*)>
<!ATTLIST p
          idx (1|2|3|4|5) #REQUIRED>

<!-- question element, optional -->
<!ELEMENT q (script,english*)>

<!-- hypothesis element -->
<!ELEMENT h (script,english*)>

<!-- miscellaneous note or comment about problem -->
<!ELEMENT note (#PCDATA)>

<!-- translation in the target language script -->
<!ELEMENT script (#PCDATA)>

<!-- transliteration of the target language translation -->
<!ELEMENT translit (#PCDATA)>

<!--morphological representation of the target language -->
<!ELEMENT morph (#PCDATA)>

<!-- original English sentence in FraCaS test suite -->
<!ELEMENT english (#PCDATA)>

=== DaisukeBekki/JSeM/data/v1.0/NewAdjective.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE jsem-dataset SYSTEM "jsem.dtd">
<?xml-stylesheet type="text/xsl" href="jsem.xsl"?>
<jsem-dataset>
  <problem answer="yes" inference_type="entailment" jsem_id="Adj1"
  language="jp" phenomena="Adjective, onazi (adjective)">
    <description>《同じ：同一性を表す「同じ」：コピュラ文》</description>
    <p idx="1">
      <script>この写真の人と、今テレビに映っている人は同じ人だ。</script>
    </p>
    <p idx="2">
      <script>この写真の人は山田だ。</script>
    </p>
    <h>
      <script>今テレビに映っている人は山田だ。</script>
    </h>
    <note></note>
  </problem>
  <problem answer="yes" inference_type="entailment" jsem_id="Adj2"
  language="jp" phenomena="Adjective, onazi (adjective)">
    <description>《同じ：同一性を表す「同じ」：コピュラ文》</description>
    <p idx="1">
      <script>太郎が一番行きたがっている大学と、花子が今通っている大学は同じ大学だ。</script>
    </p>
    <p idx="2">
      <script>太郎が一番行きたがっている大学は京都大学だ。</script>
    </p>
    <h>
      <script>花子が今通っている大学は京都大学だ。</script>
    </h>
    <note></note>
  </problem>
  <problem answer="yes" inference_type="entailment" jsem_id="Adj3"
  language="jp" phenomena="Adjective, onazi (adjective)">
    <description>《同じ：同一性を表す「同じ」：コピュラ文》</description>
    <p idx="1">
      <script>太郎が最初に結婚したときの年齢と、花子に長男が生まれたときの年齢は同じだ。</script>
    </p>
    <p idx="2">
      <script>太郎が最初に結婚したときの年齢は31歳だ。</script>
    </p>
    <h>
      <script>花子に長男が生まれたときの年齢は31歳だ。</script>
    </h>
    <note></note>
  </problem>
  <problem answer="yes" inference_type="entailment" jsem_id="Adj4"
  language="jp" phenomena="Adjective, onazi (adjective)">
    <description>《同じ：同一性を表す「同じ」：コピュラ文》</description>
    <p idx="1">
      <script>この写真の人と、今テレビに映っている人は同じ人だ。</script>
    </p>
    <p idx="2">
      <script>今テレビに映っている人は山田だ。</script>
    </p>
    <h>
      <script>この写真の人は山田だ。</script>
    </h>
    <note></note>
  </problem>
  <problem answer="yes" inference_type="entailment" jsem_id="Adj5"
  language="jp" phenomena="Adjective, onazi (adjective)">
    <description>《同じ：同一性を表す「同じ」：コピュラ文》</description>
    <p idx="1">
      <script>太郎が一番行きたがっている大学と、花子が今通っている大学は同じ大学だ。</script>
    </p>
    <p idx="2">
      <script>花子が今通っている大学は京都大学だ。</script>
    </p>
    <h>
      <script>太郎が一番行きたがっている大学は京都大学だ。</script>
    </h>
    <note></note>
  </problem>
  <problem answer="yes" inference_type="entailment" jsem_id="Adj6"
  language="jp" phenomena="Adjective, onazi (adjective)">
    <description>《同じ：同一性を表す「同じ」：コピュラ文》</description>
    <p idx="1">
      <script>太郎が最初に結婚したときの年齢と、花子に長男が生まれたときの年齢は同じだ。</script>
    </p>
    <p idx="2">
      <script>花子に長男が生まれたときの年齢は31歳だ。</script>
    </p>
    <h>
      <script>太郎が最初に結婚したときの年齢は31歳だ。</script>
    </h>
    <note></note>
  </problem>
  <problem answer="yes" inference_type="entailment" jsem_id="Adj7"
  language="jp" phenomena="Adjective, onazi (adjective)">
    <description>《同じ：同一性を表す「同じ」：非コピュラ文》</description>
    <p idx="1">
      <script>太郎と花子は同じ年に生まれた。</script>
    </p>
    <p idx="2">
      <script>太郎は1977年に生まれた。</script>
    </p>
    <h>
      <script>花子は1977年に生まれた。</script>
    </h>
    <note>常識が必要（生年は誰にとっても一つしかない）</note>
  </problem>
  <problem answer="yes" inference_type="entailment" jsem_id="Adj8"
  language="jp" phenomena="Adjective, onazi (adjective)">
    <description>《同じ：同一性を表す「同じ」：非コピュラ文》</description>
    <p idx="1">
      <script>太郎と花子は同じ県の出身だ。</script>
    </p>
    <p idx="2">
      <script>太郎は高知県の出身だ。</script>
    </p>
    <h>
      <script>花子は高知県の出身だ。</script>
    </h>
    <note>常識が必要（出身地は誰にとってもおおよそ一つ）</note>
  </problem>
  <problem answer="yes" inference_type="entailment" jsem_id="Adj9"
  language="jp" phenomena="Adjective, onazi (adjective)">
    <description>《同じ：同一性を表す「同じ」：非コピュラ文》</description>
    <p idx="1">
      <script>太郎と花子は2010年ごろに同じ部署で働いていた。</script>
    </p>
    <p idx="2">
      <script>太郎は2010年ごろに人事部で働いていた。</script>
    </p>
    <h>
      <script>花子は2010年ごろに人事部で働いていた。</script>
    </h>
    <note>常識が必要（ある時期に所属している部署は誰に取ってもおおよそ一つ）</note>
  </problem>
  <problem answer="yes" inference_type="entailment" jsem_id="Adj10"
  language="jp" phenomena="Adjective, onazi (adjective)">
    <description>《同じ：同一性を表す「同じ」：非コピュラ文》</description>
    <p idx="1">
      <script>太郎と花子は同じ年に生まれた。</script>
    </p>
    <p idx="2">
      <script>花子は1977年に生まれた。</script>
    </p>
    <h>
      <script>太郎は1977年に生まれた。</script>
    </h>
    <note>常識が必要（生年は誰にとっても一つしかない）</note>
  </problem>
  <problem answer="yes" inference_type="entailment" jsem_id="Adj11"
  language="jp" phenomena="Adjective, onazi (adjective)">
    <description>《同じ：同一性を表す「同じ」：非コピュラ文》</description>
    <p idx="1">
      <script>太郎と花子は同じ県の出身だ。</script>
    </p>
    <p idx="2">
      <script>花子は高知県の出身だ。</script>
    </p>
    <h>
      <script>太郎は高知県の出身だ。</script>
    </h>
    <note>常識が必要（出身地は誰にとってもおおよそ一つ）</note>
  </problem>
  <problem answer="yes" inference_type="entailment" jsem_id="Adj12"
  language="jp" phenomena="Adjective, onazi (adjective)">
    <description>《同じ：同一性を表す「同じ」：非コピュラ文》</description>
    <p idx="1">
      <script>太郎と花子は2010年ごろに同じ部署で働いていた。</script>
    </p>
    <p idx="2">
      <script>花子は2010年ごろに人事部で働いていた。</script>
    </p>
    <h>
      <script>太郎は2010年ごろに人事部で働いていた。</script>
    </h>
    <note>常識が必要（ある時期に所属している部署は誰に取ってもおおよそ一つ）</note>
  </problem>
  <problem answer="unknown" inference_type="" jsem_id="Adj13"
  language="jp" phenomena="Adjective, onazi (adjective)">
    <description>《同じ：同一性を表す「同じ」：非コピュラ文》</description>
    <p idx="1">
      <script>太郎と花子は同じ大学を受験した。</script>
    </p>
    <p idx="2">
      <script>太郎は東京大学を受験した。</script>
    </p>
    <h>
      <script>花子は東京大学を受験した。</script>
    </h>
    <note>常識が必要。複数の大学を受験できるという常識によりunknown</note>
  </problem>
  <problem answer="unknown" inference_type="" jsem_id="Adj14"
  language="jp" phenomena="Adjective, onazi (adjective)">
    <description>《同じ：同一性を表す「同じ」：非コピュラ文》</description>
    <p idx="1">
      <script>太郎と花子は同じ先生から空手を習った。</script>
    </p>
    <p idx="2">
      <script>太郎は大山先生から空手を習った。</script>
    </p>
    <h>
      <script>花子は大山先生から空手を習った。</script>
    </h>
    <note>常識が必要。複数の先生から空手を習えるという常識によりunknown</note>
  </problem>
  <problem answer="unknown" inference_type="" jsem_id="Adj15"
  language="jp" phenomena="Adjective, onazi (adjective)">
    <description>《同じ：同一性を表す「同じ」：非コピュラ文》</description>
    <p idx="1">
      <script>太郎は花子と次郎を同じ観光地に連れて行った。</script>
    </p>
    <p idx="2">
      <script>太郎は花子を浅草に連れて行った。</script>
    </p>
    <h>
      <script>太郎は次郎を浅草に連れて行った。</script>
    </h>
    <note>常識が必要。複数の観光地に行けるという常識によりunknown</note>
  </problem>
  <problem answer="unknown" inference_type="" jsem_id="Adj16"
  language="jp" phenomena="Adjective, onazi (adjective)">
    <description>《同じ：同一性を表す「同じ」：非コピュラ文》</description>
    <p idx="1">
      <script>太郎と花子は同じ大学を受験した。</script>
    </p>
    <p idx="2">
      <script>花子は東京大学を受験した。</script>
    </p>
    <h>
      <script>太郎は東京大学を受験した。</script>
    </h>
    <note>常識が必要。複数の大学を受験できるという常識によりunknown</note>
  </problem>
  <problem answer="unknown" inference_type="" jsem_id="Adj17"
  language="jp" phenomena="Adjective, onazi (adjective)">
    <description>《同じ：同一性を表す「同じ」：非コピュラ文》</description>
    <p idx="1">
      <script>太郎と花子は同じ先生から空手を習った。</script>
    </p>
    <p idx="2">
      <script>花子は大山先生から空手を習った。</script>
    </p>
    <h>
      <script>太郎は大山先生から空手を習った。</script>
    </h>
    <note>常識が必要。複数の先生から空手を習えるという常識によりunknown</note>
  </problem>
  <problem answer="unknown" inference_type="" jsem_id="Adj18"
  language="jp" phenomena="Adjective, onazi (adjective)">
    <description>《同じ：同一性を表す「同じ」：非コピュラ文》</description>
    <p idx="1">
      <script>太郎は花子と次郎を同じ観光地に連れて行った。</script>
    </p>
    <p idx="2">
      <script>太郎は次郎を浅草に連れて行った。</script>
    </p>
    <h>
      <script>太郎は花子を浅草に連れて行った。</script>
    </h>
    <note>常識が必要。複数の観光地に行けるという常識によりunknown</note>
  </problem>
  <problem answer="yes" inference_type="entailment" jsem_id="Adj19"
  language="jp" phenomena="Adjective, onazi (adjective)">
    <description>
    《同じ：必ずしも個体としての同一性ではなく、種類としての同一性を表す「同じ」：コピュラ文》</description>
    <p idx="1">
      <script>太郎が今日本屋で買った本と花子が昨日図書館で借りてきた本は同じ本だ。</script>
    </p>
    <p idx="2">
      <script>太郎が今日本屋で買った本は『指輪物語』だ。</script>
    </p>
    <h>
      <script>花子が昨日図書館で借りてきた本は『指輪物語』だ。</script>
    </h>
    <note></note>
  </problem>
  <problem answer="unknown" inference_type="" jsem_id="Adj20"
  language="jp" phenomena="Adjective, onazi (adjective)">
    <description>
    《同じ：必ずしも個体としての同一性ではなく、種類としての同一性を表す「同じ」：コピュラ文》</description>
    <p idx="1">
      <script>太郎が今日本屋で買った本と花子が昨日図書館で借りてきた本は同じ本だ。</script>
    </p>
    <p idx="2">
      <script>太郎が今日本屋で買った本は表紙が少し痛んでいた。</script>
    </p>
    <h>
      <script>花子が昨日図書館で借りてきた本は表紙が少し痛んでいた。</script>
    </h>
    <note></note>
  </problem>
  <problem answer="yes" inference_type="entailment" jsem_id="Adj21"
  language="jp" phenomena="Adjective, onazi (adjective)">
    <description>
    《同じ：必ずしも個体としての同一性ではなく、種類としての同一性を表す「同じ」：コピュラ文》</description>
    <p idx="1">
      <script>
      昨日の試飲会で太郎が一番美味しいと思ったワインと、今日の試飲会で花子が一番まずいと思ったワインは同じワインだ。</script>
    </p>
    <p idx="2">
      <script>昨日の試飲会で太郎が一番美味しいと思ったワインは、ペトリュスだ。</script>
    </p>
    <h>
      <script>今日の試飲会で花子が一番まずいと思ったワインは、ペトリュスだ。</script>
    </h>
    <note></note>
  </problem>
  <problem answer="unknown" inference_type="" jsem_id="Adj22"
  language="jp" phenomena="Adjective, onazi (adjective)">
    <description>
    《同じ：必ずしも個体としての同一性ではなく、種類としての同一性を表す「同じ」：コピュラ文》</description>
    <p idx="1">
      <script>
      昨日の試飲会で太郎が一番美味しいと思ったワインと、今日の試飲会で花子が一番まずいと思ったワインは同じワインだ。</script>
    </p>
    <p idx="2">
      <script>昨日の試飲会で太郎が一番美味しいと思ったワインは、状態が良かった。</script>
    </p>
    <h>
      <script>今日の試飲会で花子が一番まずいと思ったワインは、状態が良かった。</script>
    </h>
    <note></note>
  </problem>
  <problem answer="yes" inference_type="entailment" jsem_id="Adj23"
  language="jp" phenomena="Adjective, onazi (adjective)">
    <description>
    《同じ：必ずしも個体としての同一性ではなく、種類としての同一性を表す「同じ」：コピュラ文》</description>
    <p idx="1">
      <script>太郎がここ最近通勤に使っている車と、花子がおととい購入した車は同じ車だ。</script>
    </p>
    <p idx="2">
