=== DaisukeBekki/JSeM/data/jsem.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT jsem-problems (problem|comment)+>

<!-- miscellaneous comment, not necessarily on a specific problem -->
<!ELEMENT comment (#PCDATA)>

<!ELEMENT problem (link?,p+,q?,h,a?,note*)>

<!-- problem -->
<!ATTLIST problem
  jsem_id CDATA #REQUIRED
  answer (yes|no|unknown|undef) #IMPLIED
  jsem_nonstandard (true) #IMPLIED
  language (fa|de|zh|ja|jp) #IMPLIED
  phenomena CDATA #IMPLIED
  inference_type (entailment|presupposition|CI|GCI|PCI) #IMPLIED
  >

<!-- link element shows the information of corresponding FraCaS entry -->
<!ELEMENT link (#PCDATA)>
<!ATTLIST link
  resource CDATA #REQUIRED
  link_id CDATA #REQUIRED
  translation (yes|no|unknown) #IMPLIED
  same_phenomena (yes|no|unknown) #IMPLIED
  >
	  
<!-- premise elements, possibly more than one -->
<!ELEMENT p (script,english*)>
<!ATTLIST p
          idx (1|2|3|4|5) #REQUIRED>

<!-- question element, optional -->
<!ELEMENT q (script,english*)>

<!-- hypothesis element -->
<!ELEMENT h (script,english*)>

<!-- miscellaneous note or comment about problem -->
<!ELEMENT note (#PCDATA)>

<!-- translation in the target language script -->
<!ELEMENT script (#PCDATA)>

<!-- transliteration of the target language translation -->
<!ELEMENT translit (#PCDATA)>

<!--morphological representation of the target language -->
<!ELEMENT morph (#PCDATA)>

<!-- original English sentence in FraCaS test suite -->
<!ELEMENT english (#PCDATA)>

=== DaisukeBekki/JSeM/data/v1.0/Attitudes.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE jsem-problems SYSTEM "jsem.dtd">
<?xml-stylesheet type="text/xsl" href="jsem.xsl"?>
<jsem-problems>
  <problem answer="YES" inference_type="&quot;presupposition&quot;"
  jsem_id="730" language="jp" phenomena="attitude, factive">
    <link resource="fracas" />
    <p idx="1">
      <script>スミスはITELが1992年に契約を結んだことを知らなかった。</script>
    </p>
    <h>
      <script>ITELは1992年に契約を結んだ。</script>
    </h>
    <note></note>
  </problem>
  <problem answer="YES" inference_type="&quot;presupposition&quot;"
  jsem_id="731" language="jp" phenomena="attitude, factive">
    <link resource="fracas" />
    <p idx="1">
      <script>スミスはITELが1992年に契約を結んだのを知っていた。</script>
    </p>
    <h>
      <script>ITELは1992年に契約を結んだ。</script>
    </h>
    <note></note>
  </problem>
  <problem answer="YES" inference_type="&quot;presupposition&quot;"
  jsem_id="732" language="jp" phenomena="attitude, factive">
    <link resource="fracas" />
    <p idx="1">
      <script></script>
    </p>
    <p idx="2">
      <script>スミスはITELが1992年に契約を結んだのを知らなかった。</script>
    </p>
    <p idx="3">
      <script></script>
    </p>
    <h>
      <script>ITELは1992年に契約を結んだ。</script>
    </h>
    <note></note>
  </problem>
  <problem answer="UNKNOWN" inference_type="&quot;entailment&quot;"
  jsem_id="733" language="jp" phenomena="attitude, factive">
    <link resource="fracas" />
    <p idx="1">
      <script></script>
    </p>
    <p idx="2">
      <script>スミスはITELが1992年に契約を結んだかどうかを知っていた。</script>
    </p>
    <p idx="3">
      <script></script>
    </p>
    <h>
      <script>ITELは1992年に契約を結んだ。</script>
    </h>
    <note></note>
  </problem>
  <problem answer="YES" inference_type="&quot;presupposition&quot;"
  jsem_id="734" language="jp"
  phenomena="attitude, factive, -to (complementizer)">
    <link resource="fracas" />
    <p idx="1">
      <script></script>
    </p>
    <p idx="2">
      <script>スミスはITELが1992年に契約を結んだと知っていた。</script>
    </p>
    <h>
      <script>ITELは1992年に契約を結んだ。</script>
    </h>
    <note></note>
  </problem>
  <problem answer="YES" inference_type="&quot;presupposition&quot;"
  jsem_id="735" language="jp"
  phenomena="attitude, factive, -toiukoto (complementizer)">
    <link resource="fracas" />
    <p idx="1">
      <script>スミスはITELが1992年に契約を結んだということを知っていた。</script>
    </p>
    <p idx="2">
      <script></script>
    </p>
    <h>
      <script>ITELは1992年に契約を結んだ。</script>
    </h>
    <note></note>
  </problem>
  <problem answer="YES" inference_type="&quot;presupposition&quot;"
  jsem_id="736" language="jp"
  phenomena="attitude, factive, -toiuno (complementizer)">
    <link resource="fracas" />
    <p idx="1">
      <script>スミスはITELが1992年に契約を結んだというのを知っていた。</script>
    </p>
    <h>
      <script>ITELは1992年に契約を結んだ。</script>
    </h>
    <note></note>
  </problem>
  <problem answer="YES" inference_type="&quot;presupposition&quot;"
  jsem_id="737" language="jp"
  phenomena="attitude, factive, -koto (complementizer)">
    <link resource="fracas" />
    <p idx="1">
      <script>太郎は花子が高校を卒業したことを嬉しく思った。</script>
    </p>
    <h>
      <script>花子は高校を卒業した。</script>
    </h>
    <note></note>
  </problem>
  <problem answer="UNKNOWN" inference_type="&quot;entailment&quot;"
  jsem_id="738" language="jp" phenomena="attitude, non-factive">
    <link resource="fracas" />
    <p idx="1">
      <script></script>
    </p>
    <p idx="2">
      <script>スミスはITELが1992年に契約を結んだと信じていた。</script>
    </p>
    <p idx="3">
      <script></script>
    </p>
    <h>
      <script>ITELは1992年に契約を結んだ。</script>
    </h>
    <note></note>
  </problem>
  <problem answer="UNKNOWN" inference_type="&quot;entailment&quot;"
  jsem_id="739" language="jp"
  phenomena="attitude, -toiukoto (complementizer)">
    <link resource="fracas" />
    <p idx="1">
      <script>太郎は花子が犯人であるということを否定した。</script>
    </p>
    <h>
      <script>花子は犯人である。</script>
    </h>
    <note></note>
  </problem>
  <problem answer="UNKNOWN" inference_type="&quot;entailment&quot;"
  jsem_id="740" language="jp" phenomena="attitude, non-factive">
    <link resource="fracas" />
    <p idx="1">
      <script>太郎は花子が一人っ子だと思った。</script>
    </p>
    <h>
      <script>花子は一人っ子だ。</script>
    </h>
    <note>久野(1973) p.138, 井上(1976) p.254。「ト」しかとらない。</note>
  </problem>
  <problem answer="YES" inference_type="&quot;presupposition&quot;"
  jsem_id="741" language="jp"
  phenomena="attitude, factive, -koto (complementizer)">
    <link resource="fracas" />
    <p idx="1">
      <script>太郎は花子が一人っ子であることを忘れていた。</script>
    </p>
    <h>
      <script>花子は一人っ子である。</script>
    </h>
    <note>井上(1976) p.254。</note>
  </problem>
  <problem answer="YES" inference_type="&quot;presupposition&quot;"
  jsem_id="742" language="jp"
  phenomena="attitude, factive, -no (complementizer)">
    <link resource="fracas" />
    <p idx="1">
      <script>太郎は花子が一人っ子であるのを忘れていた。</script>
    </p>
    <h>
      <script>花子は一人っ子である。</script>
    </h>
    <note>井上(1976) p.254</note>
  </problem>
  <problem answer="YES" inference_type="&quot;presupposition&quot;"
  jsem_id="743" language="jp"
  phenomena="attitude, factive, -toiukoto (complementizer)">
    <link resource="fracas" />
    <p idx="1">
      <script>太郎は花子が一人っ子であるということを忘れていた。</script>
    </p>
    <h>
      <script>花子は一人っ子である。</script>
    </h>
    <note></note>
  </problem>
  <problem answer="YES" inference_type="&quot;presupposition&quot;"
  jsem_id="744" language="jp"
  phenomena="attitude, factive, -koto (complementizer)">
    <link resource="fracas" />
    <p idx="1">
      <script>太郎は花壇の花に水をやったことを忘れていた。</script>
    </p>
    <h>
      <script>太郎は花壇の花に水をやった。</script>
    </h>
    <note>井上(1976) p.254。「水をやる」の主語が「太郎」であるとき成立。</note>
  </problem>
  <problem answer="YES" inference_type="&quot;presupposition&quot;"
  jsem_id="745" language="jp"
  phenomena="attitude, factive, -no (complementizer)">
    <link resource="fracas" />
    <p idx="1">
      <script>太郎は花壇の花に水をやったのを忘れていた。</script>
    </p>
    <h>
      <script>太郎は花壇の花に水をやった。</script>
    </h>
    <note>井上(1976) p.254。「水をやる」の主語が「太郎」であるとき成立。</note>
  </problem>
  <problem answer="UNKNOWN" inference_type="&quot;entailment&quot;"
  jsem_id="746" language="jp"
  phenomena="attitude, -no (complementizer)">
    <link resource="fracas" />
    <p idx="1">
      <script>太郎は花壇の花に水をやるのを忘れていた。</script>
    </p>
    <h>
      <script>太郎は花壇の花に水をやった。</script>
    </h>
    <note>「忘れる」は未完了時制をとると叙実述語ではなくなる。(井上(1976) p.254)</note>
  </problem>
  <problem answer="UNKNOWN" inference_type="&quot;entailment&quot;"
  jsem_id="747" language="jp"
  phenomena="attitude, non-factive, -to (complementizer)">
    <link resource="fracas" />
    <p idx="1">
      <script>太郎は花子ががさつであると嘆いた。</script>
    </p>
    <h>
      <script>花子はがさつである。</script>
    </h>
    <note>久野(1973) p.138, 井上(1976)
    p.254。「コト」をとると叙実述語、「ト」をとると非叙実述語になる。</note>
  </problem>
  <problem answer="UNKNOWN" inference_type="&quot;entailment&quot;"
  jsem_id="748" language="jp"
  phenomena="attitude, non-factive, -toiukoto (complementizer)">
    <link resource="fracas" />
    <p idx="1">
      <script>太郎は花子ががさつであるということを嘆いた。</script>
    </p>
    <h>
      <script>花子はがさつである。</script>
    </h>
    <note>久野(1973) p.138, 井上(1976)
    p.254。「コト」をとると叙実述語、「ト」をとると非叙実述語になる。</note>
  </problem>
  <problem answer="YES" inference_type="&quot;presupposition&quot;"
  jsem_id="749" language="jp"
  phenomena="attitude, factive, -koto (complementizer)">
    <link resource="fracas" />
    <p idx="1">
      <script>太郎は花子ががさつであることを嘆いた。</script>
    </p>
    <h>
      <script>花子はがさつである。</script>
    </h>
    <note>久野(1973) p.138, 井上(1976)
    p.254。「コト」をとると叙実述語、「ト」をとると非叙実述語になる。</note>
  </problem>
  <problem answer="YES" inference_type="&quot;presupposition&quot;"
  jsem_id="750" language="jp"
  phenomena="attitude, factive, -no (complementizer)">
    <link resource="fracas" />
    <p idx="1">
      <script>太郎は花子ががさつであるのを嘆いた。</script>
    </p>
    <h>
      <script>花子はがさつである。</script>
    </h>
    <note>久野(1973) p.138, 井上(1976)
    p.254。「コト」をとると叙実述語、「ト」をとると非叙実述語になる。</note>
  </problem>
  <problem answer="NO" inference_type="&quot;presupposition&quot;"
  jsem_id="751" language="jp"
  phenomena="attitude, counter-factive">
    <link resource="fracas" />
    <p idx="1">
      <script>学生達は試験が延期になったと思い違いした。</script>
    </p>
    <h>
      <script>試験は延期になった。</script>
    </h>
    <note>井上(1976) p.254。「ト」しかとらない。</note>
  </problem>
  <problem answer="YES" inference_type="&quot;entailment&quot;"
  jsem_id="752" language="jp" phenomena="attitude, adverb">
    <link resource="fracas" />
    <p idx="1">
      <script></script>
    </p>
    <p idx="2">
      <script>ITELは1992年に契約をどうにか結んだ。</script>
    </p>
    <p idx="3">
      <script></script>
    </p>
    <h>
      <script>ITELは1992年に契約を結んだ。</script>
    </h>
    <note>元の現象はimplicative verbだが、対応する動詞なし。</note>
  </problem>
  <problem answer="YES" inference_type="&quot;entailment&quot;"
  jsem_id="753" language="jp"
  phenomena="attitude, implicative verb">
    <link resource="fracas" />
    <p idx="1">
      <script>山田氏はトマトから有効成分を抽出することに成功した。</script>
    </p>
    <h>
      <script>山田氏はトマトから有効成分を抽出した。</script>
    </h>
    <note></note>
  </problem>
  <problem answer="NO" inference_type="&quot;entailment&quot;"
  jsem_id="754" language="jp"
  phenomena="attitude, negative implicative">
    <link resource="fracas" />
    <p idx="1">
      <script>太郎は7時の電車に乗り損ねた。</script>
    </p>
    <h>
      <script>太郎は7時の電車に乗った。</script>
    </h>
    <note>fail toの和訳。</note>
  </problem>
  <problem answer="YES" inference_type="&quot;entailment&quot;"
  jsem_id="755" language="jp"
  phenomena="attitude, negative implicative">
    <link resource="fracas" />
    <p idx="1">
      <script>太郎は今日は7時の電車に乗り損ねなかった。</script>
    </p>
    <h>
      <script>太郎は今日は7時の電車に乗った。</script>
    </h>
    <note>fail toの和訳。</note>
  </problem>
  <problem answer="UNKNOWN" inference_type="&quot;entailment&quot;"
